# -*- coding: utf-8 -*-
"""Nutri.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yy5fvHeLt8O_n6chLi5AwhUDhbdq27aT
"""

print('📦 Installing packages...')

print('✅ All packages installed!')

# ╔══════════════════════════════════════════╗
# ║  CELL 2 — Write the Streamlit app file   ║
# ╚══════════════════════════════════════════╝

# 👇 PASTE YOUR API KEYS HERE
#GROQ_API_KEY = "gsk_xxxxxxxxxxxxxxxx"        # 👈 Your Groq key
#HF_TOKEN     = "hf_xxxxxxxxxxxxxxxx"         # 👈 Your HuggingFace token (or leave "")
#NGROK_TOKEN  = "xxxxxxxxxxxxxxxx"            # 👈 Your ngrok token

# ─────────────────────────────────────────────────────────
#nutriscan_code = f"""
#import streamlit as st
#import requests
#import base64
#import json
#from PIL import Image

#st.set_page_config(page_title="NutriScan AI", page_icon="🥗", layout="wide", initial_sidebar_state="collapsed")

# Keys injected from Colab
#GROQ_KEY = "{GROQ_API_KEY}"
#HF_KEY   = "{HF_TOKEN}"

#st.markdown('''<style>
#@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700;900&family=Inter:wght@400;500;600&display=swap');
#html, body, [class*="css"] {{ font-family: 'Inter', sans-serif; }}
#.hero {{ background: linear-gradient(135deg, #FF6B35, #F7C59F, #EFEFD0, #004E89, #1A936F);
    #background-size: 400% 400%; animation: gradientShift 8s ease infinite;
    #border-radius: 20px; padding: 48px 32px; margin-bottom: 28px;
    #text-align: center; box-shadow: 0 8px 40px rgba(0,0,0,0.18); }}
#@keyframes gradientShift {{ 0%{{background-position:0% 50%;}} 50%{{background-position:100% 50%;}} 100%{{background-position:0% 50%;}} }}
#.hero h1 {{ font-family:'Playfair Display',serif; font-size:3rem; font-weight:900; color:#fff;
    #text-shadow:0 2px 12px rgba(0,0,0,0.30); margin:0 0 8px 0; }}
#.hero p {{ font-size:1.1rem; color:rgba(255,255,255,0.92); margin:0; }}
#.slide-container {{ background:linear-gradient(90deg,#1A1A2E,#16213E,#0F3460);
   # border-radius:16px; padding:20px; margin-bottom:24px; }}
#.slide-title {{ font-family:'Playfair Display',serif; font-size:1.5rem; color:#F7C59F; text-align:center; margin-bottom:8px; }}
#.cuisine-strip {{ display:flex; gap:16px; overflow-x:auto; padding:12px 0; scrollbar-width:none; }}
#.cuisine-item {{ flex:0 0 auto; background:rgba(255,255,255,0.1); border-radius:12px;
#    padding:14px 18px; text-align:center; border:1px solid rgba(255,255,255,0.2); min-width:100px; }}
#.cuisine-emoji {{ font-size:2.2rem; }}
#.cuisine-label {{ color:#fff; font-size:0.8rem; margin-top:6px; }}
#.nutrient-grid {{ display:flex; flex-wrap:wrap; gap:10px; margin-top:14px; }}
#.nutrient-badge {{ background:linear-gradient(135deg,#FF6B35,#FF8E53); color:white;


# ── Hero
#st.markdown(\'\'\'<div class="hero">
   # <h1>🍽️ NutriScan AI</h1>
    #<p>Upload your meal plate · Identify foods instantly · Get full nutrition · Plan your diet with AI</p>
#</div>\'\'\', unsafe_allow_html=True)

# ── Cuisine Slideshow
#cuisines = [("🍛","Indian"),("🍣","Japanese"),("🍕","Italian"),("🥘","Spanish"),
   # ("🫕","Thai"),("🥙","Lebanese"),("🌮","Mexican"),("🍜","Chinese"),
   # ("🥗","Mediterranean"),("🍲","Korean"),("🥧","French"),("🫔","Turkish"),
    #("🍱","Bento"),("🥩","BBQ"),("🧆","Middle Eastern"),("🍤","Seafood"),
    #("🥞","American"),("🫓","German"),("🥟","Dim Sum")]

#carousel_html = \'<div class="cuisine-strip">\'
#for emoji, label in cuisines:
  #  carousel_html += f\'<div class="cuisine-item"><div class="cuisine-emoji">{{emoji}}</div><div class="cuisine-label">{{label}}</div></div>\'
#carousel_html += \'</div>\'

#st.markdown(f\'\'\'<div class="slide-container">
    #<div class="slide-title">🌍 World Cuisines Explorer</div>
    #{{carousel_html}}
   # <div style="text-align:center;color:rgba(255,255,255,0.5);font-size:0.75rem;margin-top:8px;">← scroll to explore →</div>
#</div>\'\'\', unsafe_allow_html=True)

# ── Tabs
#tab1, tab2, tab3 = st.tabs(["📸  Scan My Meal", "🤖  Diet Chatbot", "📊  Nutrition Guide"])

# ════ TAB 1 ════
#with tab1:
    #col_left, col_right = st.columns([1, 1], gap="large")
    #with col_left:
      #  st.markdown("### 📸 Upload Your Meal Plate")
        #uploaded_file = st.file_uploader("Upload meal image", type=["jpg","jpeg","png","webp"], label_visibility="collapsed")
        #if uploaded_file:
           # img = Image.open(uploaded_file)
           # st.image(img, caption="Your meal plate", use_container_width=True)
           # st.success("✅ Image uploaded! Click Analyse.")
           # analyze_btn = st.button("🔍 Analyse My Meal", use_container_width=True)
        #else:
            #st.info("📷 Upload a JPG/PNG photo of your meal plate to get started")
           # analyze_btn = False

    #with col_right:
     #   st.markdown("### 🔬 Analysis Results")
      #  if analyze_btn and uploaded_file:
       #     with st.spinner("🧠 AI is analysing your meal..."):
         #       img_bytes = uploaded_file.getvalue()
         #       b64_img   = base64.b64encode(img_bytes).decode("utf-8")
         #       mime      = uploaded_file.type or "image/jpeg"

          #      hf_label = ""
          #      if HF_KEY:
           #         try:
            #            hf_resp = requests.post(
             #               "https://api-inference.huggingface.co/models/nateraw/food",
              #              headers={{"Authorization": f"Bearer {{HF_KEY}}"}},
              #              data=img_bytes, timeout=15)
               #         if hf_resp.status_code == 200:
                #            hf_data = hf_resp.json()
                 #           if isinstance(hf_data, list) and hf_data:
                  #              hf_label = hf_data[0].get("label", "")
                   # except:
                    #    pass

            #    hint   = f"HuggingFace identified this as: '{{hf_label}}'." if hf_label else ""
            #    prompt = f\"\"\"You are a professional nutritionist and food recognition AI.
#{{hint}}
#Analyse this meal plate image and respond ONLY with valid JSON:
#{{"foods_detected":["food1","food2"],"cuisine_type":"Cuisine","total_calories":520,
#"serving_size":"1 plate (~350g)","macros":{{"protein_g":28,"carbs_g":60,"fat_g":14,"fiber_g":8,"sugar_g":6}},
#"key_vitamins":["Vitamin C","Iron"],"health_score":7.5,
#"health_tags":["High Protein","Balanced"],"diet_suitability":["Vegetarian"],
#"quick_tip":"One sentence tip."}}
#Be accurate and realistic.\"\"\"



                    #if response.status_code == 200:
                     #   raw  = response.json()["choices"][0]["message"]["content"]
                      #  raw  = raw.strip().replace("```json","").replace("```","").strip()
                       # data = json.loads(raw)
#
             #                       foods   = data.get("foods_detected", [])
              #          cuisine = data.get("cuisine_type", "Unknown")
               #         st.markdown(f\'<div class="food-result">🍽️ {{", ".join(foods)}}</div>\', unsafe_allow_html=True)
                #        st.markdown(f"**Cuisine:** {{cuisine}}")

                 #       c1,c2,c3 = st.columns(3)
                  #      c1.metric("🔥 Calories",     f\'{{data.get("total_calories","–")}} kcal\')
                   #     c2.metric("⚖️ Serving",      data.get("serving_size","").split("(")[0].strip())
                    #    c3.metric("💚 Health Score", f\'{{data.get("health_score","–")}}/10\')


                       # tip = data.get("quick_tip","")
                       # if tip: st.info(f"💡 {{tip}}")
                   # else:
                       # st.error(f"API Error {{response.status_code}}: {{response.text[:300]}}")

                 #except json.JSONDecodeError:
                   # st.warning("Non-JSON response:"); st.code(raw[:500])
                #except Exception as e:
                   # st.error(f"Error: {{str(e)}}")
        #else:
           # st.info("Upload a photo and click Analyse to see results here.")

# ════ TAB 2 ════
#with tab2:
    #st.markdown("### 🤖 AI Diet & Nutrition Coach")
    #st.markdown("Ask me about diet planning, nutrition, healthy eating, or meal prep!")

    #if "chat_history" not in st.session_state:
        #st.session_state.chat_history = [{{"role":"assistant",
           # "content":"👋 Hi! I am your AI Nutritionist. Ask me about meal plans, calories, nutrition facts, or diet advice!"}}]

   # for msg in st.session_state.chat_history:
        #if msg["role"] == "user":
            #st.markdown(f\'<div class="chat-user">👤 {{msg["content"]}}</div>\', unsafe_allow_html=True)
        #else:
            #content = msg["content"].replace("\\n","<br>")
            #st.markdown(f\'<div class="chat-bot">🤖 {{content}}</div>\', unsafe_allow_html=True)



    #if final_input:
       # st.session_state.chat_history.append({{"role":"user","content":final_input}})
       # sys_prompt  = "You are NutriBot, a warm expert AI nutritionist. Give evidence-based practical advice. Use bullet points and emojis."
        #api_messages = [{{"role":"system","content":sys_prompt}}]
        #for m in st.session_state.chat_history[-10:]:
           # api_messages.append({{"role":m["role"],"content":m["content"]}})
        #with st.spinner("NutriBot is thinking..."):
            #try:
                #resp = requests.post("https://api.groq.com/openai/v1/chat/completions",
                   # headers={{"Authorization":f"Bearer {{GROQ_KEY}}","Content-Type":"application/json"}},
                    #json={{"model":"llama-3.3-70b-versatile","messages":api_messages,"max_tokens":700,"temperature":0.7}},
                    #timeout=30)

    #with col_a:
        #st.markdown("#### 🔢 Daily Calorie Calculator")
        #gender   = st.radio("Gender", ["Male","Female"], horizontal=True)
        #age      = st.slider("Age", 15, 80, 25)
        #weight   = st.number_input("Weight (kg)", min_value=30.0, max_value=200.0, value=70.0)
        #height   = st.number_input("Height (cm)", min_value=100.0, max_value=220.0, value=170.0)
        #activity = st.selectbox("Activity Level", ["Sedentary","Light (1-3x/week)","Moderate (3-5x/week)","Active (6-7x/week)","Very Active"])
        #goal     = st.selectbox("Goal", ["Maintain Weight","Lose Weight","Gain Muscle"])
        #if st.button("Calculate 🔥"):
            #bmr    = (10*weight+6.25*height-5*age+5) if gender=="Male" else (10*weight+6.25*height-5*age-161)
           # mults  = {{"Sedentary":1.2,"Light (1-3x/week)":1.375,"Moderate (3-5x/week)":1.55,"Active (6-7x/week)":1.725,"Very Active":1.9}}
            #tdee   = bmr * mults.get(activity,1.375)
            #target = tdee-500 if goal=="Lose Weight" else (tdee+300 if goal=="Gain Muscle" else tdee)
            #tag    = "500 kcal deficit" if goal=="Lose Weight" else ("300 kcal surplus" if goal=="Gain Muscle" else "Maintenance")
            #st.success(f"**Daily Target: {{int(target)}} kcal** ({{tag}})\\n\\n| Macro | Amount |\\n|---|---|\\n| 🥩 Protein | {{int(target*0.30/4)}}g |\\n| 🍚 Carbs | {{int(target*0.45/4)}}g |\\n| 🥑 Fat | {{int(target*0.25/9)}}g |")

    #with col_b:
        #st.markdown("#### 🥦 Key Nutrients")
        #for name,emoji,rda,sources in [
            #("Protein","🥩","0.8–1.6g/kg","Chicken, fish, eggs, lentils"),
            #("Carbohydrates","🍚","45–65% calories","Rice, oats, fruits"),
            #("Healthy Fats","🥑","20–35% calories","Olive oil, nuts, avocado"),
            #("Fiber","🌾","25–38g/day","Whole grains, legumes, vegetables"),
            #("Vitamin C","🍊","65–90mg/day","Citrus, berries, peppers"),
            #("Iron","🩸","8–18mg/day","Red meat, spinach, legumes"),
            #("Calcium","🥛","1000–1200mg/day","Dairy, tofu, almonds"),
            #("Vitamin D","☀️","600–800 IU/day","Sunlight, fatty fish, egg yolks")]:
            #with st.expander(f"{{emoji}} {{name}}"):
                #st.markdown(f"**RDA:** {{rda}}\\n\\n**Sources:** {{sources}}")

#st.markdown("---")
#st.markdown("<div style='text-align:center;color:#aaa;font-size:0.82rem;'>🍽️ NutriScan AI — Powered by Groq LLaMA 4 + HuggingFace | Built with Streamlit</div>", unsafe_allow_html=True)
#"""

#with open("nutriscan_app.py", "w") as f:
    #f.write(nutriscan_code)

#print("✅ App file written: nutriscan_app.py")

import streamlit as st
import base64 as _b64 

# Force-inject secrets directly into the decoder to bypass caching issues
GROQ_API_KEY = st.secrets["GROQ_API_KEY"]
HF_TOKEN = st.secrets["HF_TOKEN"]

_code = _b64.b64decode(_app_b64).decode("utf-8")
_code = _code.replace("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", GROQ_API_KEY)
_code = _code.replace("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", HF_TOKEN)

# Mock pyngrok to prevent it from crashing your Streamlit Cloud environment
import sys
from types import ModuleType
mock_ngrok = ModuleType("pyngrok")
mock_ngrok.ngrok = ModuleType("ngrok")
mock_ngrok.conf = ModuleType("conf")
sys.modules["pyngrok"] = mock_ngrok
sys.modules["pyngrok.ngrok"] = mock_ngrok.ngrok
sys.modules["pyngrok.conf"] = mock_ngrok.conf

# Launch the app interface seamlessly
exec(_code, globals())



